version: '3.9'
name: minilink
services:
  minilink:
    build:
      context: miniLink
    environment:
      - MONGO_CONN_URI

  frontend:
    build:
      context: ./frontend

    restart: unless-stopped

  # Connectors
  proxy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - minilink
      - frontend
