version: '3.9'
name: minilink
services:
  minilink:
    build:
      context: miniLink
    restart: unless-stopped
    environment:
      - MONGO_CONN_URI

  frontend:
    build:
      context: ./frontend

    restart: unless-stopped

  # Connectors
  proxy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - minilink
      - frontend

  # This configuration uses Cloudflared Tunnels to expose the program to the internet without me port forwarding. You can remove this if you'd like.
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN
    depends_on:
      - proxy